# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('facebook_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
